# Generated by Django 5.2.1 on 2025-08-06 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_alter_empleado_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondeoCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50)),
                ('importe_cheque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='GastoCajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fondeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja_chica.fondeocajachica')),
            ],
        ),
        migrations.CreateModel(
            name='ValeCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('fondeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja_chica.fondeocajachica')),
            ],
        ),
    ]
