# Generated by Django 5.2.1 on 2025-08-07 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0001_initial'),
        ('gastos', '0003_alter_tipogasto_empresa'),
        ('proveedores', '0004_alter_proveedor_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastocajachica',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='gastocajachica',
            name='tipo_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.tipogasto'),
        ),
    ]
