# Generated by Django 5.2.1 on 2025-08-07 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0002_gastocajachica_proveedor_gastocajachica_tipo_gasto'),
        ('empresas', '0003_alter_empresa_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondeocajachica',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
