# Generated by Django 5.2.1 on 2025-08-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0003_fondeocajachica_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='valecaja',
            name='autorizado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='valecaja',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
