# Generated by Django 5.2.1 on 2025-08-07 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0004_valecaja_autorizado_por_valecaja_recibido_por'),
        ('gastos', '0003_alter_tipogasto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='valecaja',
            name='tipo_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.tipogasto'),
        ),
    ]
