# Generated by Django 5.2.1 on 2025-06-04 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(max_length=100)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('superficie_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ocupado', 'Ocupado'), ('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento')], default='ocupado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'numero')},
            },
        ),
    ]
