# Generated by Django 5.2.1 on 2025-06-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomun',
            name='id',
        ),
        migrations.AddField(
            model_name='areacomun',
            name='num_contrato',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='ubicacion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
