# Generated by Django 5.2.1 on 2025-06-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_remove_areacomun_id_areacomun_num_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
