# Generated by Django 5.2.1 on 2025-06-04 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_areacomun_fecha_fin_areacomun_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomun',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='fecha_inicio',
        ),
    ]
