# Generated by Django 5.2.1 on 2025-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_remove_areacomun_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
    ]
