# Generated by Django 5.2.1 on 2025-06-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_alter_areacomun_cliente'),
        ('clientes', '0002_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
