# Generated by Django 5.2.1 on 2025-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_alter_areacomun_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
