# Generated by Django 5.2.1 on 2025-06-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_areacomun_fecha_fin_areacomun_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacomun',
            old_name='fecha_inicio',
            new_name='fecha_inicial',
        ),
    ]
