# Generated by Django 5.2.1 on 2025-06-04 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0011_alter_areacomun_cliente'),
        ('clientes', '0002_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
