# Generated by Django 5.2.1 on 2025-06-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0013_alter_areacomun_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='giro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
