# Generated by Django 5.2.1 on 2025-06-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0015_remove_areacomun_num_contrato_areacomun_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='deposito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
