# Generated by Django 5.2.1 on 2025-06-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0016_areacomun_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='tipo_area',
            field=models.CharField(choices=[('Modulo', 'modulo'), ('Stand', 'stand'), ('Superficie', 'superficie'), ('Isla', 'isla'), ('Cajon', 'cajon')], default='Modulo', max_length=20),
        ),
    ]
