# Generated by Django 5.2.1 on 2025-06-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0017_areacomun_tipo_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='cantidad_areas',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='tipo_area',
            field=models.CharField(choices=[('Modulo', 'modulo'), ('Stand', 'stand'), ('Espacio', 'superficie'), ('Isla', 'isla'), ('Cajon', 'cajon'), ('Area', 'area')], default='Modulo', max_length=20),
        ),
    ]
