# Generated by Django 5.2.1 on 2025-06-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
