# Generated by Django 5.2.1 on 2025-06-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('locales', '0002_localcomercial_activo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localcomercial',
            unique_together={('empresa', 'numero')},
        ),
    ]
