# Generated by Django 5.2.1 on 2025-06-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0005_alter_localcomercial_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localcomercial',
            name='observaciones',
            field=models.CharField(blank=True, null=True),
        ),
    ]
