# Generated by Django 5.2.1 on 2025-06-04 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_unique_together'),
        ('locales', '0007_alter_localcomercial_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
