# Generated by Django 5.2.1 on 2025-06-05 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_unique_together'),
        ('locales', '0008_alter_localcomercial_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='propietario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localcomercial',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
