# Generated by Django 5.2.1 on 2025-06-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0010_alter_localcomercial_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='giro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
