# Generated by Django 5.2.1 on 2025-06-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_factura_fecha_vencimiento_factura_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='periodo',
            new_name='fecha_vencimiento',
        ),
    ]
