# Generated by Django 5.2.1 on 2025-06-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_rename_periodo_factura_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='observaciones',
            field=models.CharField(blank=True, null=True),
        ),
    ]
