# Generated by Django 5.2.1 on 2025-06-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('credito', 'Crédito'), ('efectivo', 'Efectivo'), ('deposito', 'Depósito'), ('otro', 'Otro')], default='transferencia', max_length=20),
        ),
    ]
