# Generated by Django 5.2.1 on 2025-06-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_facturaauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito'), ('deposito', 'Depósito'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='transferencia', max_length=20),
        ),
    ]
