# Generated by Django 5.2.1 on 2025-06-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturaAuditoria',
        ),
    ]
