# Generated by Django 5.2.1 on 2025-06-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_delete_facturaauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_cuota',
            field=models.CharField(choices=[('renta', 'Renta'), ('renta_garantia', 'Deposito Garantía'), ('cuota', 'Mantenimiento'), ('cuota_servicio', 'Servicios'), ('cuota_extra', 'Extraordinaria'), ('cuota_penalidad', 'Penalidad'), ('cuota_publicidad', 'Publicidad')], default='local', max_length=20),
        ),
    ]
