# Generated by Django 5.2.1 on 2025-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_factura_tipo_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='folio',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_cuota',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('renta', 'Renta'), ('deposito garantia', 'Deposito Garantía'), ('servicios', 'Servicios'), ('extraordinaria', 'Extraordinaria'), ('penalidad', 'Penalidad'), ('publicidad', 'Publicidad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito'), ('deposito', 'Depósito'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='transferencia', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
