# Generated by Django 5.2.1 on 2025-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_alter_factura_folio_alter_factura_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_cuota',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('renta', 'Renta'), ('deposito garantia', 'Deposito Garantía'), ('servicios', 'Servicios'), ('extraordinaria', 'Extraordinaria'), ('penalidad', 'Penalidad'), ('publicidad', 'Publicidad')], default='mantenimiento', max_length=100),
        ),
    ]
