# Generated by Django 5.2.1 on 2025-06-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_alter_factura_tipo_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/'),
        ),
    ]
