# Generated by Django 5.2.1 on 2025-06-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_pago_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fact_sat',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='facturas/fact_sat/'),
        ),
    ]
