# Generated by Django 5.2.1 on 2025-06-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_factura_fact_sat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fact_sat',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='fact_sat/'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
