# Generated by Django 5.2.1 on 2025-06-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_alter_factura_fact_sat_alter_pago_comprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fact_sat',
            new_name='cfdi',
        ),
    ]
