# Generated by Django 5.2.1 on 2025-06-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_rename_fact_sat_factura_cfdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
