# Generated by Django 5.2.1 on 2025-06-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_pago_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrada', 'Cobrada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
