# Generated by Django 5.2.1 on 2025-06-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_unique_together'),
        ('empresas', '0001_initial'),
        ('facturacion', '0021_alter_factura_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_cuota',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('renta', 'Renta'), ('deposito garantia', 'Deposito Garantía'), ('extraordinaria', 'Extraordinaria'), ('penalidad', 'Multa'), ('intereses', 'Intereses')], max_length=100),
        ),
        migrations.CreateModel(
            name='FacturaOtrosIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ingreso', models.CharField(choices=[('estacionamiento', 'Estacionamiento'), ('sanitario', 'Sanitarios'), ('propineros', 'Propineros'), ('publicidad', 'Publicidad'), ('servicios', 'Servicios'), ('otros', 'Otros')], max_length=20)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('cfdi', models.FileField(blank=True, max_length=255, null=True, upload_to='fact_sat/')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrada', 'Cobrada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.CharField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
