# Generated by Django 5.2.1 on 2025-06-30 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_alter_factura_tipo_cuota_facturaotrosingresos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroOtrosIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_cobro', models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito'), ('deposito', 'Depósito'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='transferencia', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='facturacion.facturaotrosingresos')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
