# Generated by Django 5.2.1 on 2025-07-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_alter_cobrootrosingresos_comprobante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobrootrosingresos',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='facturaotrosingresos',
            name='cfdi',
        ),
        migrations.AddField(
            model_name='cobrootrosingresos',
            name='comprobante_oi',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='facturaotrosingresos',
            name='cfdi_oi',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='fact_sat/'),
        ),
    ]
