# Generated by Django 5.2.1 on 2025-07-09 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('facturacion', '0028_alter_cobrootrosingresos_comprobante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('origen', models.CharField(choices=[('local', 'Locales'), ('area', 'Áreas comunes'), ('otros', 'Otros ingresos')], max_length=10)),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'anio', 'mes', 'origen')},
            },
        ),
    ]
