# Generated by Django 5.2.1 on 2025-07-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0029_presupuestoingreso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresupuestoIngreso',
        ),
    ]
