# Generated by Django 5.2.1 on 2025-07-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0031_tipootroingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaotrosingresos',
            name='tipo_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipootroingreso'),
        ),
    ]
