# Generated by Django 5.2.1 on 2025-07-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0032_alter_facturaotrosingresos_tipo_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipootroingreso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
