# Generated by Django 5.2.1 on 2025-08-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_cuenta_bancaria'),
        ('facturacion', '0033_alter_tipootroingreso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='folio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('folio', 'empresa')},
        ),
    ]
