# Generated by Django 5.2.1 on 2025-08-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0034_alter_factura_folio_alter_factura_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(),
        ),
    ]
