# Generated by Django 5.2.1 on 2025-06-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('puesto', models.CharField(choices=[('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('JEFE', 'Jefe'), ('AUX', 'Auxiliar'), ('OPERATIVO', 'Operativo'), ('OTRO', 'Otro')], max_length=30)),
                ('departamento', models.CharField(choices=[('ADMIN', 'Administracion'), ('CONTA', 'Contabilidad'), ('MANTTO', 'Mantenimiento'), ('EST', 'Estacionamiento'), ('LIMP', 'Limpieza'), ('SEG', 'Seguridad'), ('OTRO', 'Otro')], max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
    ]
