# Generated by Django 5.2.1 on 2025-08-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rfc',
            field=models.CharField(max_length=13),
        ),
    ]
