# Generated by Django 5.2.1 on 2025-06-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('empresa', 'rfc')},
        ),
    ]
