# Generated by Django 5.2.1 on 2025-07-08 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('principal', '0004_evento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
