# Generated by Django 5.2.1 on 2025-07-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_evento_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('demo', 'Demo'), ('premium', 'Premium'), ('admin', 'Admin')], default='demo', max_length=20),
        ),
    ]
