# Generated by Django 5.2.1 on 2025-07-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('demo', 'Demo'), ('pago', 'Pago'), ('gratis', 'Gratis')], default='demo', max_length=20),
        ),
    ]
