# Generated by Django 5.2.1 on 2025-07-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
