# Generated by Django 5.2.1 on 2025-07-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_perfilusuario_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
