# Generated by Django 5.2.1 on 2025-07-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_perfilusuario_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='mostrar_wizard',
            field=models.BooleanField(default=False),
        ),
    ]
