# Generated by Django 5.2.1 on 2025-08-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_nombre_alter_proveedor_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
