# Generated by Django 5.2.1 on 2025-07-18 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cuenta_bancaria_empresa_numero_cuenta_and_more'),
        ('gastos', '002_default_grupos_subgrupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipogasto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
