# Generated by Django 5.2.1 on 2025-07-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_cuenta_bancaria_empresa_numero_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, choices=[('BANAMEX', 'Banamex'), ('BANCOMER', 'Bancomer'), ('SANTANDER', 'Santander'), ('HSBC', 'HSBC'), ('BBVA', 'BBVA'), ('IXE', 'Ixe'), ('SCOTIABANK', 'Scotiabank'), ('BANORTE', 'Banorte'), ('INBURSA', 'Inbursa'), ('BANCOPPEL', 'Bancoppel'), ('AFIRME', 'Afirme'), ('BAJIO', 'Bajío'), ('MULTIVA', 'Multiva'), ('OTRO', 'Otro')], max_length=100, null=True),
        ),
    ]
